# Generated by Django 2.2.3 on 2019-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
