# Generated by Django 2.2.3 on 2019-07-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190703_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records', to='core.Habit'),
        ),
    ]
